### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [sonatard/werror#1]
Hi, first of all, thanks for a nice library!

Could you add LICENSE file?

The following pages might help for choosing a license.

* [Choose an open source license | Choose a License](https://choosealicense.com/)
* [Githubによる、オープンソースライセンスの選び方 | オープンソース・ライセンスの談話室](https://www.catch.jp/oss-license/2013/09/10/github/)

I hope you choose a permissive license like MIT or BSD.
Thanks!

**Comment by sonatard** [comment]
Thanks!!

**Comment by hnakamur** [comment]
Thanks for sharing a nice library with permissive license!
